### ISSUE TITLE
Passeio automático

### ISSUE THREAD

**Issue by brunobg** [Corollarium/lajevr#47]
Definir um tour automático, que fique eternamente dando voltas.

- [x] tempo esperado: mais ou menos uns 3-5 minutos. Como o mergulhador nada bem devagar não precisa ser um path muito longo.
- [x] sugiro começar em cima da água. mais ou menos como está agora. Tem um botinho e um barco de modelos e seria legal usar um deles, mas não sei se funciona daí pq o cara teria que "subir no barco" de novo, veja se fica direito isso.
- [x] passar perto e por cima do Moreia (o naufrágio).
- [x] sugestão de implementar: ou desenhar o path no blender e importar, ou usar o sistema de bezier com pontos chave igual no `loadTurtle()`.
- [x] tem que ter uma tecla para entrar em modo automático ou sair dele. Espaço pode ser. Nada contra pular pro ponto zero se apertar a tecla, corte seco mesmo.

**Comment by hiperlogic** [comment]
Pensei em pegar o que você fez pra tartaruga...
Uma coisa que estou pensando: 3 animações:
1- Caindo na água (sem loop)
2- Passeio (com loop)
3- Saindo da água (sem loop)

Do 3 vai pra 1 caso queira novo passeio
